version: 2
updates:
  # Automatic upgrade for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Automatic upgrade for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  # Automatic upgrade for base images used in the Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"